In [41]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import numpy as np

In [42]:
load_dotenv()
engine = create_engine(os.getenv("SUPABASE_DB_URL"))

query = "SELECT * FROM weather_logs ORDER BY timestamp ASC;"
df = pd.read_sql(query, con=engine)
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m,created_at
0,2026-09-10 00:00:00+00:00,20.017500,80.0,0.0,997.721802,0.0,21.599998,308.0,19.117563,100.0,37.079998,2026-09-10 18:59:15.051899+00:00
1,2026-09-10 01:00:00+00:00,19.367500,74.0,0.0,998.480835,0.0,23.759998,316.0,17.427710,99.0,44.279999,2026-09-10 18:59:15.051899+00:00
2,2026-09-10 02:00:00+00:00,18.117500,73.0,0.0,998.225281,0.0,19.440001,318.0,16.302025,100.0,43.199997,2026-09-10 18:59:15.051899+00:00
3,2026-09-10 03:00:00+00:00,17.817501,77.0,0.0,998.901550,0.0,18.000000,312.0,16.397026,46.0,33.119999,2026-09-10 18:59:15.051899+00:00
4,2026-09-10 04:00:00+00:00,17.967501,75.0,0.0,999.500305,0.0,17.280001,303.0,16.560665,88.0,33.119999,2026-09-10 18:59:15.051899+00:00

In [43]:
cols=["temperature_2m","surface_pressure","wind_speed_10m","apparent_temperature","wind_gusts_10m","rain","precipitation"]
df[cols]=df[cols].round(2)
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m,created_at
0,2026-09-10 00:00:00+00:00,20.02,80.0,0.0,997.72,0.0,21.60,308.0,19.12,100.0,37.08,2026-09-10 18:59:15.051899+00:00
1,2026-09-10 01:00:00+00:00,19.37,74.0,0.0,998.48,0.0,23.76,316.0,17.43,99.0,44.28,2026-09-10 18:59:15.051899+00:00
2,2026-09-10 02:00:00+00:00,18.12,73.0,0.0,998.23,0.0,19.44,318.0,16.30,100.0,43.20,2026-09-10 18:59:15.051899+00:00
3,2026-09-10 03:00:00+00:00,17.82,77.0,0.0,998.90,0.0,18.00,312.0,16.40,46.0,33.12,2026-09-10 18:59:15.051899+00:00
4,2026-09-10 04:00:00+00:00,17.97,75.0,0.0,999.50,0.0,17.28,303.0,16.56,88.0,33.12,2026-09-10 18:59:15.051899+00:00

In [44]:
df=df.drop("created_at",axis=1)
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m
0,2026-09-10 00:00:00+00:00,20.02,80.0,0.0,997.72,0.0,21.60,308.0,19.12,100.0,37.08
1,2026-09-10 01:00:00+00:00,19.37,74.0,0.0,998.48,0.0,23.76,316.0,17.43,99.0,44.28
2,2026-09-10 02:00:00+00:00,18.12,73.0,0.0,998.23,0.0,19.44,318.0,16.30,100.0,43.20
3,2026-09-10 03:00:00+00:00,17.82,77.0,0.0,998.90,0.0,18.00,312.0,16.40,46.0,33.12
4,2026-09-10 04:00:00+00:00,17.97,75.0,0.0,999.50,0.0,17.28,303.0,16.56,88.0,33.12

In [40]:
df["timestamp"] = df["timestamp"].dt.strftime("%Y-%m-%d %H:%M")
df.head()

,timestamp,temperature_2m,relative_humidity_2m,rain,surface_pressure,precipitation,wind_speed_10m,wind_direction_10m,apparent_temperature,cloud_cover,wind_gusts_10m
0,2026-09-10 00:00,20.02,80.0,0.0,997.72,0.0,21.60,308.0,19.12,100.0,37.08
1,2026-09-10 01:00,19.37,74.0,0.0,998.48,0.0,23.76,316.0,17.43,99.0,44.28
2,2026-09-10 02:00,18.12,73.0,0.0,998.23,0.0,19.44,318.0,16.30,100.0,43.20
3,2026-09-10 03:00,17.82,77.0,0.0,998.90,0.0,18.00,312.0,16.40,46.0,33.12
4,2026-09-10 04:00,17.97,75.0,0.0,999.50,0.0,17.28,303.0,16.56,88.0,33.12

In [45]:
table_name = "weather_logs_cleaned"
df.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",  # ha már létezik a tábla, írja felül (futtathatod többször is)
    index=False,           # ne mentse el a pandas indexet külön oszlopként
    method="multi"         # felgyorsítja a nagy mennyiségű adat beszúrását
)

168